#!/bin/bash
#SBATCH --job-name=gretaRun
#SBATCH --time=00:30:00         
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --partition=batch,long

#SBATCH --output=logs/%j_%x.out
#SBATCH --error=logs/%j_%x.err

# -------------------------
# Input and environment
# -------------------------
TARGET=$1                        
CONDA_ENV="greta"

mkdir -p logs

echo "[JOB START] $(date)"
echo "Node: $(hostname)"
echo "JobID: $SLURM_JOB_ID"

# Load conda and activate environment
module load Anaconda3/2024.02-1
source /opt/sw/noarch/softwares/Anaconda3/2024.02-1/etc/profile.d/conda.sh
conda activate $CONDA_ENV

# Run Snakemake workflow
snakemake --profile config/slurm/ $TARGET

echo "[JOB END] $(date)"

# dts/hg38/pbmc10k/smpl.frags.tsv.gz